### ISSUE TITLE
Best Method of Communication?

### ISSUE THREAD

**Issue by michaelorr** [FizzBuzzClub/fizzbuzz.club#2]
I wanted to get thoughts on best method of communication that folks preferred.
I have avoided making an internal slack channel at work since a) I want to keep this as a personal project and b) I didn't want to preclude anyone who doesn't work at our same company.
So, the way I see it, we could:
1) Make a slack channel in Tech404 (the Atlanta regional slack org)
2) Make a channel in irc on freenode
3) Just use github issues
Drawbacks to (1) and (2) is that some folks in here are not avid users of those platforms. I've got an irc client/account but I login every day for a week and then not for months at a time...
Drawback to (3) is that all the conversations would be public (since this repo is public) and it is much more difficult to have "realtime" conversations.
What are other ideas that I haven't thought of? Thoughts?

**Comment by brimstone** [comment]
:+1: to freenode or tech404

Github Issues are ok, but they're tired to a repo (or meta-repo) and end up more long form, thus end up sounding more formal.

**Comment by michaelorr** [comment]
Yeah, github issues are a common denominator, but they have their own drawbacks... I think I'm personally leaning towards a tech404 channel since we can a) make it private b) most folks will already have the slack app on their phones and can customize notifications specifically for that channel, so it doesnt add much overhead or noise.
I've gone ahead and made a private tech404 channel #fizzbuzzclub. Everyone except @shaunduncan @devnall and @tebriel had accounts that were easy enough to find and folks have been invited. If someone has another idea or solution, we can always shutter that channel and I'd be more than happy to do so. I know a few folks here will probably be more in favor of irc, but I'm just not sure if that is quite as universally used by everyone here.

**Comment by michaelorr** [comment]
Seems like there were no complaints about the tech404 channel. I'll go ahead and close this.
